spring:
    application:
        name: spring-batch-workshop
    datasource:
        write:
            url: ${DB_WRITE_URL}
            username: ${DB_WRITE_USERNAME}
            password: ${DB_WRITE_PASSWORD}
            driver-class-name: org.postgresql.Driver
        read:
            url: ${DB_READ_URL}
            username: ${DB_READ_USERNAME}
            password: ${DB_READ_PASSWORD}
            driver-class-name: org.postgresql.Driver
    batch:
        jdbc:
            initialize-schema: always
server:
    port: 5432
