INSERT INTO medical_appointments (id, doctor_email, doctor_firstname, doctor_lastname, patient_email, patient_firstname, patient_lastname, ailments, recommendations)
VALUES
    (gen_random_uuid(), 'dr.johnsmith@example.com', 'John', 'Smith', 'patient.jane@example.com', 'Jane', 'Doe', 'General checkup', 'Healthy lifestyle recommendations'),
    (gen_random_uuid(), 'dr.johnsmith@example.com', 'John', 'Smith', 'patient.karen@example.com', 'Karen', 'Harris', 'General checkup', 'Healthy lifestyle recommendations'),
    (gen_random_uuid(), 'dr.johnsmith@example.com', 'John', 'Smith', 'patient.nina@example.com', 'Nina', 'Perez', 'General checkup', 'Healthy lifestyle recommendations'),
    (gen_random_uuid(), 'dr.johnsmith@example.com', 'John', 'Smith', 'patient.andrew@example.com', 'Andrew', 'Miller', 'General checkup', 'Healthy lifestyle recommendations'),
    (gen_random_uuid(), 'dr.johnsmith@example.com', 'John', 'Smith', 'patient.victoria@example.com', 'Victoria', 'King', 'General checkup', 'Healthy lifestyle recommendations'),
    (gen_random_uuid(), 'dr.sarahjones@example.com', 'Sarah', 'Jones', 'patient.michael@example.com', 'Michael', 'Johnson', 'Flu symptoms', 'Take prescribed medication'),
    (gen_random_uuid(), 'dr.sarahjones@example.com', 'Sarah', 'Jones', 'patient.sophia@example.com', 'Sophia', 'Martinez', 'Flu symptoms', 'Take prescribed medication'),
    (gen_random_uuid(), 'dr.sarahjones@example.com', 'Sarah', 'Jones', 'patient.peter@example.com', 'Peter', 'Davis', 'Flu symptoms', 'Take prescribed medication'),
    (gen_random_uuid(), 'dr.emilybrown@example.com', 'Emily', 'Brown', 'patient.emily@example.com', 'Emily', 'White', 'Back pain', 'Physical therapy exercises'),
    (gen_random_uuid(), 'dr.mikeadams@example.com', 'Mike', 'Adams', 'patient.peter@example.com', 'Peter', 'Davis', 'Stomach ache', 'Avoid certain foods'),
    (gen_random_uuid(), 'dr.lisawilson@example.com', 'Lisa', 'Wilson', 'patient.mary@example.com', 'Mary', 'Williams', 'Allergy symptoms', 'Allergy test recommended'),
    (gen_random_uuid(), 'dr.patrickmiller@example.com', 'Patrick', 'Miller', 'patient.susan@example.com', 'Susan', 'Martinez', 'Headache', 'Drink more water'),
    (gen_random_uuid(), 'dr.oliverthomas@example.com', 'Oliver', 'Thomas', 'patient.james@example.com', 'James', 'Anderson', 'Diabetes', 'Continue medication'),
    (gen_random_uuid(), 'dr.sophiamoore@example.com', 'Sophia', 'Moore', 'patient.alex@example.com', 'Alex', 'Garcia', 'Cold and cough', 'Rest and fluids'),
    (gen_random_uuid(), 'dr.noahjohnson@example.com', 'Noah', 'Johnson', 'patient.sophia@example.com', 'Sophia', 'Martinez', 'High blood pressure', 'Reduce salt intake'),
    (gen_random_uuid(), 'dr.lucasmartin@example.com', 'Lucas', 'Martin', 'patient.anna@example.com', 'Anna', 'Lopez', 'High cholesterol', 'Low-fat diet advised'),
    (gen_random_uuid(), 'dr.nataliebrown@example.com', 'Natalie', 'Brown', 'patient.andrew@example.com', 'Andrew', 'Miller', 'Fatigue', 'Blood tests recommended'),
    (gen_random_uuid(), 'dr.davidlee@example.com', 'David', 'Lee', 'patient.karen@example.com', 'Karen', 'Harris', 'Arthritis', 'Anti-inflammatory treatment'),
    (gen_random_uuid(), 'dr.laurenhall@example.com', 'Lauren', 'Hall', 'patient.katie@example.com', 'Katie', 'Clark', 'Anxiety', 'Counseling suggested'),
    (gen_random_uuid(), 'dr.zachmartin@example.com', 'Zach', 'Martin', 'patient.john@example.com', 'John', 'Scott', 'Sleep disorder', 'Melatonin supplement advised'),
    (gen_random_uuid(), 'dr.jenniferwright@example.com', 'Jennifer', 'Wright', 'patient.nina@example.com', 'Nina', 'Perez', 'Skin rash', 'Use prescribed ointment'),
    (gen_random_uuid(), 'dr.matthewrodriguez@example.com', 'Matthew', 'Rodriguez', 'patient.rachel@example.com', 'Rachel', 'Green', 'Injury from fall', 'Apply cold compress'),
    (gen_random_uuid(), 'dr.samanthadavis@example.com', 'Samantha', 'Davis', 'patient.alex@example.com', 'Alex', 'Taylor', 'Chest pain', 'EKG test recommended'),
    (gen_random_uuid(), 'dr.paulmartin@example.com', 'Paul', 'Martin', 'patient.chloe@example.com', 'Chloe', 'Nelson', 'Fatigue', 'Iron supplement recommended'),
    (gen_random_uuid(), 'dr.gracewilson@example.com', 'Grace', 'Wilson', 'patient.daniel@example.com', 'Daniel', 'Young', 'Joint pain', 'Orthopedic consultation suggested'),
    (gen_random_uuid(), 'dr.julianmurphy@example.com', 'Julian', 'Murphy', 'patient.victoria@example.com', 'Victoria', 'King', 'Eye infection', 'Antibiotic eye drops prescribed');
